### ISSUE TITLE
LogRPC does not launch after downloading files

### ISSUE THREAD

**Issue by Shararamosh** [LogicismDev/LogRPC#5]
The first time I runned LogRPC after installing it on Windows 11 Pro, it said "handshake failed", the next time it downloaded files, but didn't do anything else. On all subsequent runs it just does not do anything - not even appearing in Task Manager.
When opening LogRPCUpdater.exe, it shows "A Java exception has occured" error message from Java Virtual Machine Launcher.
I have Java Version 8 Update 421 installed.

**Comment by Shararamosh** [comment]
I've installed it using LogRPC-Setup.exe. Here's the output from console prompt:
`ёхэ 26, 2024 6:27:32 PM com.jagrosh.discordipc.entities.pipe.Pipe openPipe
INFO: Found preferred client: STABLE
{"assets":{"large_image":"https://i.imgur.com/HApEahS.gif","large_text":"LogRPC v1.93"},"buttons":[{"label":"Download my Work","url":"https://logicism.tv/downloads/"},{"label":"Buy a Gaming/Anime Banner","url":"https://www.fiverr.com/logicism/design-a-youtube-or-twitch-banner-and-logo-made-for-gamers"}],"instance":false,"timestamps":{},"details":"LogRPC v1.93","state":"Coded in Java and JavaScript"}
ёхэ 26, 2024 6:27:32 PM org.java_websocket.server.WebSocketServer handleFatal
SEVERE: Shutdown due to fatal error
java.net.BindException: Address already in use: bind
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
        at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
        at org.java_websocket.server.WebSocketServer.doSetupSelectorAndServerThread(WebSocketServer.java:533)
        at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:341)
        at java.lang.Thread.run(Unknown Source)

java.net.BindException: Address already in use: bind
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
        at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
        at org.java_websocket.server.WebSocketServer.doSetupSelectorAndServerThread(WebSocketServer.java:533)
        at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:341)
        at java.lang.Thread.run(Unknown Source)
Success`

**Comment by Shararamosh** [comment]
Okay, I tried manually removing Java and re-installing it and LogRPC started working.
